org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft 与 Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings (Mojmap 官方映射)
mapping_channel=official
mapping_version=1.20.1

# Mod 元信息
mod_id=shinoyuki_accesshub
mod_name=AccessHub
mod_license=AGPL-3.0
mod_version=0.2.5
mod_group_id=com.shinoyuki.accesshub
mod_authors=Shinoyuki
mod_description=Whitelist management and game info HTTP API for dedicated Minecraft servers (Forge 1.20.1).
