# ConvenientAccess Plugin Configuration

# HTTP服务器配置
http:
  # 是否启用HTTP服务器
  enabled: true
  # 监听端口
  port: 22222
  # 监听地址 (0.0.0.0 表示所有接口)
  host: "0.0.0.0"
  # 最大线程数
  max-threads: 10
  # 连接超时时间 (毫秒)
  timeout: 30000

# API配置
api:
  # API版本
  version: "v1"
  # 简化认证配置
  auth:
    # 管理员密码（首次启动时自动生成）
    admin-password: ""
    # 默认API Token（用于测试）
    default-token: "test_token_123456"
  # 请求频率限制 (每分钟最大请求数)
  rate-limit:
    enabled: false
    requests-per-minute: 60
  # 是否启用CORS
  cors:
    enabled: true
    allowed-origins: ["*"]

# 白名单管理配置
whitelist:
  # 注册令牌默认过期时间 (小时)
  token-expiry-hours: 24
  # 是否自动清理过期令牌
  auto-cleanup-tokens: true

# 数据缓存配置
cache:
  # 服务器基本信息缓存时间 (秒)
  server-info: 300
  # 性能数据缓存时间 (秒)
  performance: 5
  # 玩家数据缓存时间 (秒)
  players: 10
  # 世界数据缓存时间 (秒)
  worlds: 60

# Spark集成配置
spark:
  # 是否优先使用Spark API
  prefer-spark: true
  # Spark API超时时间 (毫秒)
  timeout: 5000

# 日志配置
logging:
  # 是否记录API请求日志
  log-requests: true
  # 是否记录详细错误信息
  debug: true