# ConvenientAccess Plugin Configuration

# HTTP服务器配置
http:
  # 是否启用HTTP服务器
  enabled: true
  # 监听端口
  port: 22222
  # 监听地址 (0.0.0.0 表示所有接口)
  host: "0.0.0.0"
  # 最大线程数
  max-threads: 10
  # 连接超时时间 (毫秒)
  timeout: 30000

# API配置
api:
  # API版本
  version: "v1"
  # 认证配置
  auth:
    # 是否启用API鉴权（建议生产环境开启）
    enabled: true
    # 管理员密码（首次启动时自动生成，设置后保持不变）
    admin-password: ""
    # API访问令牌（首次启动时自动生成sk-开头的64位token）
    api-token: ""
    # 令牌前缀（不建议修改）
    token-prefix: "sk-"
    # 登录失败限制 (防止暴力破解)
    login-attempt-limit:
      # 是否启用登录失败限制
      enabled: true
      # 最大失败尝试次数
      max-attempts: 5
      # 锁定时长 (分钟)
      lock-duration-minutes: 15
  # 请求频率限制 (每分钟最大请求数)
  rate-limit:
    enabled: false
    requests-per-minute: 60
  # 是否启用CORS
  cors:
    enabled: true
    allowed-origins: ["*"]

# 白名单管理配置
whitelist:
  # 是否启用白名单功能
  enabled: true
  # 严格模式（验证失败时拒绝连接，建议开启用于调试）
  strict-mode: true
  # 踢出消息（支持颜色代码 &）
  kick-message: |
    &c您不在服务器白名单中！
    &7请联系管理员申请加入白名单
  # 联系方式信息
  contact-info: "请联系管理员"
  # 注册令牌默认过期时间 (小时)
  token-expiry-hours: 24
  # 是否自动清理过期令牌
  auto-cleanup-tokens: true
  # 玩家加入通知
  join-notification:
    # 是否启用管理员通知
    enabled: true
    # 需要的权限节点
    permission: "convenientaccess.whitelist.notify"
  # 欢迎消息
  welcome-message:
    # 是否启用欢迎消息
    enabled: true
    # 欢迎消息内容（支持颜色代码 &）
    text: |
      &a欢迎回到服务器！
      &7玩家: &e{player}
      &7服务器: &e{server}

# 数据缓存配置
cache:
  # 服务器基本信息缓存时间 (秒)
  server-info: 300
  # 性能数据缓存时间 (秒)
  performance: 5
  # 玩家数据缓存时间 (秒)
  players: 10
  # 世界数据缓存时间 (秒)
  worlds: 60

# Spark集成配置
spark:
  # 是否优先使用Spark API
  prefer-spark: true
  # Spark API超时时间 (毫秒)
  timeout: 5000

# 日志配置
logging:
  # 是否记录API请求日志
  log-requests: true
  # 是否记录详细错误信息
  debug: true

# 备份配置
backup:
  # 是否启用自动备份
  enabled: true
  # 备份时间配置 - 支持两种格式:
  # 1. 简单格式: "d:h:m" (天:小时:分钟), 例如 "1:2:30" 表示每1天2小时30分钟备份一次
  # 2. 详细格式(已废弃): time.hour 和 time.minute
  schedule: "0:2:0"  # 默认每天凌晨2点备份
  # 备份保留天数
  retention-days: 7
  # 是否压缩备份为ZIP格式
  compress: true