name: ConvenientAccess
version: 0.1.0
main: com.xaoxiao.convenientaccess.ConvenientAccessPlugin
api-version: "1.20"
author: xaoxiao
description: A convenient server information access plugin with whitelist management for Minecraft 1.20.1 Arclight servers
website: https://github.com/xaoxiao/convenient-access

softdepend:
  - spark

commands:
  convenientaccess:
    description: ConvenientAccess plugin commands
    aliases: [ca, capi]
    usage: /<command> [reload|status|help|whitelist]
    permission: convenientaccess.admin

permissions:
  convenientaccess.admin:
    description: Allows access to ConvenientAccess admin commands
    default: op
  convenientaccess.whitelist.read:
    description: Allows reading whitelist data
    default: op
  convenientaccess.whitelist.write:
    description: Allows modifying whitelist data
    default: op
  convenientaccess.whitelist.notify:
    description: Receives notifications when whitelisted players join
    default: op
  convenientaccess.whitelist.bypass:
    description: Bypass whitelist restrictions
    default: false
  convenientaccess.api.access:
    description: Allows access to ConvenientAccess API
    default: true
  convenientaccess.api.sensitive:
    description: Allows access to sensitive server information
    default: op